#Import Libraries
library(rattle)

#Import Data

#C:\Users\hitej\Documents\March Madness\MarchMadnessFullData-Clean.csv
data <- read.csv(file.choose())

#===========================================================================
# Need to match games
# Build split into training and validation data
# Build NN
# Run teams and opponents in groups and validate against actual results 
# ==========================================================================

#Clean Data
data$Home_Team <- as.character(data$Home_Team)
data$URL <- as.character(data$URL)

game <- matrix(nrow = 9545)

#Finds matching games
for (i in 1:9545){
  if(length(which((data$Home_Team[i] == data$URL) &
                  data$HT_Pts[i] == data$Opp_Pts))>0){
  game[i] <- which((data$Home_Team[i] == data$URL) &
     data$HT_Pts[i] == data$Opp_Pts)
  } else {
    game[i] <- 0
  }
}

game2 <- matrix(nrow=9545)
game <- cbind(game, game2)
rm(game2)

#Indexes Matching Games
x <- 1
for(i in 1:9545){
  if(game[i] > 0){
      game[i,2] <- x
      game[game[i,1],2] <- x
      x <- x+1
  } else {
    game[i, 2] <- 0
  }
}

game <- as.data.frame(game)
colnames(game) <- c("Column", "Game_Index")

data <- cbind(data, game$Game_Index)
colnames(data)[22] <- "Game_Index"

#Removes Games Against DivII Teams
DivI <- subset(data, data$Game_Index != 0)
DivI <- subset(DivI, DivI$URL != "#N/A")

#Write to CSV and Transform in Excel
write.csv(DivI, file.choose())

#Import Transformed Data
#C:\Users\hitej\Documents\March Madness\DivI_Wide_1.csv and DivI_Wide_2.csv
DivI_1 <- read.csv(file.choose())
DivI_2 <- read.csv(file.choose())
fullData <- rbind(DivI_1, DivI_2)

#Model in Rattle
#rattle()
#=================================================
# Below is the training code generated by Rattle
#=================================================

# Load an R data frame.

crs$dataset <- fullData

# Display a simple summary (structure) of the dataset.

str(crs$dataset)
set.seed(55)

crs$nobs     <- nrow(crs$dataset)
crs$train    <- crs$sample <- sample(crs$nobs, 0.7*crs$nobs)
crs$validate <- sample(setdiff(seq_len(crs$nobs), crs$train), 0.15*crs$nobs)
crs$test     <- setdiff(setdiff(seq_len(crs$nobs), crs$train), crs$validate)

# The following variable selections have been noted.

crs$input     <- c("FG", "FGA", "FG_Pct", "Three_Pt", "Three_Pt_Attempts",
                   "Three_Pt_Pct", "Free_Throws", "Free_Throw_Attempts",
                   "Free_Throw_Pct", "Offensive_Rebounds", "Total_Rebounds",
                   "Assists", "Steals", "Blocks", "Turnovers",
                   "Personal_Fouls", "FG_Opp", "FGA_Opp", "FG_Pct_Opp",
                   "Three_Pt_Opp", "Three_Pt_Attempts_Opp", "Three_Pt_Pct_Opp",
                   "Free_Throws_Opp", "Free_Throw_Attempts_Opp",
                   "Free_Throw_Pct_Opp", "Offensive_Rebounds_Opp",
                   "Total_Rebounds_Opp", "Assists_Opp", "Steals_Opp",
                   "Blocks_Opp", "Turnovers_Opp", "Personal_Fouls_Opp")

crs$numeric   <- c("FG", "FGA", "FG_Pct", "Three_Pt", "Three_Pt_Attempts",
                   "Three_Pt_Pct", "Free_Throws", "Free_Throw_Attempts",
                   "Free_Throw_Pct", "Offensive_Rebounds", "Total_Rebounds",
                   "Assists", "Steals", "Blocks", "Turnovers",
                   "Personal_Fouls", "FG_Opp", "FGA_Opp", "FG_Pct_Opp",
                   "Three_Pt_Opp", "Three_Pt_Attempts_Opp", "Three_Pt_Pct_Opp",
                   "Free_Throws_Opp", "Free_Throw_Attempts_Opp",
                   "Free_Throw_Pct_Opp", "Offensive_Rebounds_Opp",
                   "Total_Rebounds_Opp", "Assists_Opp", "Steals_Opp",
                   "Blocks_Opp", "Turnovers_Opp", "Personal_Fouls_Opp")

crs$categoric <- NULL

crs$target    <- "Result"
crs$risk      <- NULL
crs$ident     <- c("Game_Index", "Home_Team", "URL")
crs$ignore    <- c("HT_Pts", "Opp_Pts")
crs$weights   <- NULL

library(kernlab, quietly=TRUE)

# Build a Support Vector Machine model.

set.seed(crv$seed)
crs$ksvm <- ksvm(as.factor(Result) ~ .,
                 data=crs$dataset[crs$train,c(crs$input, crs$target)],
                 kernel="vanilladot",
                 prob.model=TRUE)

# Generate a textual view of the SVM model.

crs$ksvm


#Create New Data to Score

modelTeams <- function(team1, team2){
  home <- subset(data, data$Home_Team == team1)
  home <- home[,c(1,4,6:22)]
  opp <- subset(data, data$Home_Team == team1)
  opp <- opp[,c(1,4,6:22)]
  columns <- c("Game_Index", "Home_Team", "URL", "HT_Pts", "Opp_Pts", "FG", "FGA", "FG_Pct",
               "Three_Pt", "Three_Pt_Attempts", "Three_Pt_Pct", "Free_Throws", "Free_Throw_Attempts",
               "Free_Throw_Pct", "Offensive_Rebounds", "Total_Rebounds", "Assists", "Steals", "Blocks", "Turnovers",
               "Personal_Fouls", "FG_Opp", "FGA_Opp", "FG_Pct_Opp", "Three_Pt_Opp", "Three_Pt_Attempts_Opp",
               "Three_Pt_Pct_Opp", "Free_Throws_Opp", "Free_Throw_Attempts_Opp", "Free_Throw_Pct_Opp",
               "Offensive_Rebounds_Opp", "Total_Rebounds_Opp", "Assists_Opp", "Steals_Opp", "Blocks_Opp", "Turnovers_Opp",
               "Personal_Fouls_Opp", "Result")
  temp <- cbind(home[sample.int(nrow(home), 20),], 
                opp[sample.int(nrow(opp), 20),])
  temp <- temp[,c(19, 1, 20, 2, 21, 3:18, 22:37)]
  temp$results <- NA
  colnames(temp) <- columns
  pr <- kernlab::predict(crs$ksvm, newdata=temp)
  temp$Result <- pr
  return(summary(temp$Result))
}

modelGames <- function(team1, team2){
  result <- matrix(nrow = 200, ncol = 2)
  for(i in 1:200){
    temp <- modelTeams(team1, team2)
    result[i,1] <- temp[1]
    result[i,2] <- temp[2]
  }
  probability <- colSums(result)[2]/4000
  odds <- probability/(1-probability)
  return(c(probability, odds))
  
}




